openapi: 3.0.1
info:
  title: Revolut challenge bank account API
  version: 1.0.0
paths:
  /transfer:
    put:
      tags:
      - transfer
      summary: Transfer currency between two accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
        required: true
      responses:
        200:
          description: Ok
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        412:
          description: Balance update changed during transaction. Try again later
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /account:
    post:
      tags:
      - account
      summary: Open a new bank account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        201:
          description: Created
          headers:
            ETag:
              schema:
                type: string
                example: '"5"'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /account/{accountNumber}:
    parameters:
    - name: accountNumber
      in: path
      required: true
      schema:
        type: string
        example: 12345678-12345678
    get:
      tags:
      - account
      summary: Read bank account details
      responses:
        200:
          description: Ok
          headers:
            ETag:
              schema:
                type: string
                example: '"5"'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
      - account
      summary: Update bank account balance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccount'
      responses:
        200:
          description: Ok
          headers:
            ETag:
              schema:
                type: string
                example: '"5"'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        412:
          description: Balance update changed during transaction. Try again later
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - account
      summary: Close bank account
      parameters:
      - name: If-Match
        required: true
        in: header
        schema:
          type: string
          example: '"0"'
      responses:
        204:
          description: No Content
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        412:
          description: Account changed before delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        428:
          description: If-Match header is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Account:
      type: object
      properties:
        account:
          type: string
          example: 12345678-12345678-12345678
        balance:
          type: number
    Transfer:
      type: object
      properties:
        from:
          type: string
          example: 12345678-12345678-12345678
        to:
          type: string
          example: 87654321-87654321
        amount:
          type: number
    UpdateAccount:
      type: object
      properties:
        withdraw:
          type: number
        deposit:
          type: number
    Error:
      type: object
      properties:
        code:
          type: string
          example: NO_CREDIT_ACCOUNT
